os: linux
language: android
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-google-android-support
jdk: oraclejdk8
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - fonts-droid
before_script:
- wget https\://services.gradle.org/distributions/gradle-4.4-bin.zip
- unzip -qq gradle-4.4-bin.zip
- export GRADLE_HOME=$PWD/gradle-4.4
- export PATH=$GRADLE_HOME/bin:$PATH
- git clone https://github.com/flutter/flutter.git
script:
- "./flutter/bin/flutter -v build apk"
cache:
  directories:
  - "$HOME/.pub-cache"
before_install:
- yes | sdkmanager "platforms;android-27"
- openssl aes-256-cbc -K $encrypted_d056db0bbbce_key -iv $encrypted_d056db0bbbce_iv
  -in key.properties.enc -out android/key.properties -d
deploy:
  provider: releases
  api_key:
    secure: g1P8mBxpBAd0RMATa6zaK/QpWgUT4R3mwqoEvU3pXHcDXevCc3sI/H7w9WB4/u1ltS/lxvWYM+rXl5EXUwitSPpFFLITFQj4+YoK9UYiVH07zPMAFo3uQqlkJ8d1BjhxNFX+uVkg7qJZcgLO4oFHnorXK7vVfSlnJJcv8O3HcNEvaK228YEfRm5xPgN0m/8wCyfjUc91/p1grXO2a6MecP05LUCxWXRw6AAah3bv0B4ME3/tPd3wi7kR9yybbR8sZDTa4gIMRFEySa49AAxh2YOsl8Rp8x/IStTCzzXJQnbYnqAaIf7lnlY2mGi7C9pkLMVTkjdnkPIcpnD9tzu8fuDE0EyvsL39LMQia1Y0JFsdZAD2Jbr+ZIgVlJdvyUebowUkoVBQWAo4A+C26geEqqA8GTCtOCTlaLH2cM9s8gxwNjp9Qc0oR8ClVxvUmRBKDrUBzl0R5KvwxYQKfScN2JNaeAMuU7mNmmwodQMBIe/ljyWkGfz0x1TgThk/0O4tWCWkg3d39pT+N2AkN9q1zXXpwUkZqdcdKkpKVgSwZfz8uwF/ZkX2I2PKMpW5htXKRJL8pKKvAeaE8nQK5Xot9TvtDt2WtuAgeSMgKhyy05ZN+9qRhMTKKh4e6KahjGbM6ENA3FsPUxvBbOOTGFVTX0GF8oZFAixMuV1M/brG2Qg=
  file: build/app/outputs/apk/release/app-release.apk
  on:
    repo: ruihuancao/flutter_movie
    tags: true
    all_branches: true

